### PR TITLE
Move completions to new testing infrastructure

### LINKED ISSUE #59: Move completions to new compiler testing infrastructure
In #51  and #55 we moved signatureHelp and hover to a new testing infrastructure. This new infrastructure makes it very productive to polish the output from the presentation compiler using `~metaserver/testOnly -- tests.compiler`. This workflow is way more productive than doing `publishLocal`, open vscode, manually type code and see what it produces.

The completion provider can also benefit from some polishing in how the completions are ordered, for example that fields of a class take prioritity over defaults like `toString`/`finalize`

### PR DESCRIPTION
**Pull request by gabro**
Still WIP.

This closes #59. I've picked up @olafurpg's work and simply changed the implementation to use `safeCompletionsAt`. I'll add some extra test cases and merge this, so that we can use it as a base for #62 and #63

### CODE REVIEW

**Comment by olafurpg** [comment]
I just checked out your branch and got it working with _CURSOR_, that seems to fix the StringIndexOutOfBounds error. Will soon push a fix!

**Comment by olafurpg** [comment]
I made the enough changes to get the case test passing, we can leave further completion improvements to #63 and #62

**Comment by olafurpg** [comment]
I'm still not happy with the code organization for the compiler. It seems we should delegate to CompletionProvider/SignatureHelpProvider/HoverProvider to create the compilation unit, since they have different needs for _CURSOR_. I will try to refactor things a bit more.

**Comment by olafurpg** [comment]
- Compiler is now ScalacProvider and does nothing but return an interactive.Global
- logic for SignatureHelp/Completions/Hover providers is now fully contained in those objects, with exact same implementation being shared for tests and from the server

I hope this makes sense. There is still quite a bit of duplication for the three providers that can be abstracted away by changing the superclass LanguageServer, but we can leave that for later.

The signature help bug fix is there because I thought it was a regression from the refactorings, sorry for mixing that together.

**Comment by olafurpg** [comment]
PS, can you maybe open PRs from your personal fork @gabro ? it seems CI runs test on every push to any branch on origin.

**Comment by olafurpg** [comment]
Seems CI is unhappy :(

> oci runtime error: exec failed: container_linux.go:265: starting container process caused "could not create session key: disk quota exceeded"

Will try to restart tomorrow!

**Comment by gabro** [comment]
@olafurpg ah sure, I've been opening on the main repo out of habit at work, but I didn't realize Travis would notify you. I'll use my fork from now on.

Also, thanks for the nice refactoring. I think it makes sense to delegate responsibility over the compiler configuration to the single providers.
I wouldn't worry about duplicating code for now: it's way easier to deduplicate later, than to tangle a huge mess like it was about to become. 👍

**Comment by olafurpg** [comment]
Having a well-defined API between the server and Global will become even more important once we add support for multiple scala versions via classloading. Travis is happy now :D

**Comment by laughedelic** [comment]
I'm also used to open PRs from the branches in the repo itself at work (isn't it the main point for giving the collaborator permissions?). Anyway, if it's just about Travis notifications, I usually just rurn them off:

```yaml
notifications:
  email: false
```

Or it can be configured for only certain emails and only certain events:

```yaml
notifications:
  email:
    recipients:
      - one@example.com
      - other@example.com
    on_success: never  # default: change
    on_failure: change # default: always
```

Also [docs](https://docs.travis-ci.com/user/notifications/#Configuring-email-notifications) say that 
> Pull Request builds do not trigger email notifications

So the problem is in deduplicating the triggering events: `pr` only for PRs, `push` only for master. I think I know how to solve it.

**Comment by gabro** [comment]
I think there's no need to complicate the Travis settings, if the alternative is using a fork model for PRs. I wouldn't lose too much time on this :)

**Comment by olafurpg** [comment]
Another aspect is that I typically try to keep the number of branches in the origin fork clean. Contributors who fork the repo pull all branches and I don't like it I fetch 100s of WIP branches (many forgotten and will never get merged) when contributing to a project. `master` and `gh-pages` is cleaner, IMO

**Comment by laughedelic** [comment]
Makes sense 👍

**Pull request merged**
